name: "Feature request"
description: "Teile uns deine Idee(n) mit!"
title: "[Vorschlag]: "
labels: []
assignees:
  - Ceddix
body:
  - type: input
    id: name
    attributes:
      label: "Minecraft Name"
      description: "Wie lautet dein Name in Minecraft?"
      placeholder: "ex. Ceddix"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Was soll passieren?"
      description: "Beschreibe detailliert und aufschlussreich, was du dir vorstellst."
    validations:
      required: true
  - type: textarea
    id: issue-related
    attributes:
      label: "Hat dein Vorschlag etwas mit einem Fehler zu tun?"
      description: "Beschreibe genau worum es geht. z.B.: \"Es ist immer unpraktisch wenn...\""
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "Hast du Alternativen in Erwägung gezogen?"
      description: "Beschreibe uns ggf. aus deiner Sicht mögliche Alternativen."
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: "Zusätzliche Informationen"
      description: "Füge Weblinks, Screenshots, alles was mit der Idee zu tun hat und Informationen und Eindrücke liefern kann hier ein."
    validations:
      required: false
